vpc_name              = "my-vpc"
vpc_cidr              = "10.10.0.0/16"
subnet_name           = "my-subnet"
subnet_cidr           = "10.10.10.0/24"
availability_zone     = "us-east-1a"
internet_gateway_name = "my-internet-gateway"